title:              Evan Stoddard
email:              evan.stoddard@me.com
description:        Embedded Engineer | Nashville, TN
author:             Evan Stoddard
baseurl:            "/"
url:                "https://evanstoddard.github.io"

# Social Profiles
github_username:    evanstoddard
instagram_username: evanrstoddard
linkedin_username: evan-stoddard

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
